 # Backend/customer-service/src/main/resources/application.yml
spring:
  application:
    name: customer-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false