spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

eureka:
  client:
    enabled: false


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

file:
  upload:
    directory: C:\Users\Approxy\Desktop\s\sosyalMediaProject\kaydedilenResimler\test-uploads
    allowed-extensions: jpg,jpeg,png,gif,pdf,mp4,avi,mov,doc,docx

logging:
  level:
    com.sosyalmedia.customerservice: INFO