 # analytics-service/src/main/resources/application.yml

spring:
  application:
    name: analytics-service

  # Config Server
  config:
    import: configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6
        multiplier: 1.1